
# Author: Jacob Nabe-Nielsen
# Date: 27 August 2020
# Version 0.9
# Licence GPL v3
# Description: Methods and classes for reading and summarizing DEPONS raster
#   objects


#' @title  DeponsDyn-class and methods
#' @description Classes and methods for analyzing and plotting output from the
#' DEPONS model.
#' @slot title Character  Name of the object or simulation (character)
#' @slot landscape Character  Identifier for the landscape used in the DEPONS
#' simulations. The landscapes 'DanTysk', 'Gemini', 'Kattegat', 'North Sea',
#' 'Homogeneous', and 'User defined' are distributed with the DEPONS model.
#' @slot simdate POSIXlt object with the date and time when the simulation was
#' finished. This is read from the name of the imput file.
#' @slot crs CRS object providing the coordinate reference system used; see
#' \link[sp]{CRS} for details
#' @slot simstart POSIXlt object with the first day of the simulation, i.e.
#' the first day in the period that the simulations are intended to represent in
#' the real world.
#' @slot data Data frame with simulation output.
#' @details The following columns are included in the simulation output data
#' frame: 'tick', which indicates the number of half-hourly time steps since the
#' start of the simulation; 'count', which indicates the population size at a
#' given time; 'energy', showing the average amount of energy stored by simulated
#' animals, and 'lenergy' which shows the total amount of energy in the landscape.
#' @exportClass DeponsDyn
#' @examples a.DeponsDyn <- new("DeponsDyn")
#' a.DeponsDyn
#' @note DeponsDyn-objects are usually read in from csv files produced during
#' DEPONS simulations.
#' @note Use data(bathymetry) to load example data.
setClass(Class="DeponsDyn",
         slots=list(title="character", landscape="character", simdate="POSIXlt",
                    crs="character", simstart="POSIXlt", data="data.frame")
)


setMethod("initialize", "DeponsDyn",
          function(.Object) {
            .Object@title <- "NA"
            .Object@landscape <- "NA"
            .Object@simdate <- as.POSIXlt(NA)
            .Object@crs <- "NA"
            .Object@simstart <- as.POSIXlt(NA)
            .Object@data <- data.frame("tick"=NA, "count"=NA, "energy"=NA, "lenergy"=NA)
            return((.Object))
          }
)


setMethod("show", "DeponsDyn",
          function(object) {
            cat("class:    \t", "DeponsDyn \n")
            cat("title:    \t", object@title, "\n")
            cat("landscape:\t", object@landscape, "\n")
            cat("simdate:  \t", as.character(object@simdate), "\n")
            cat("crs:      \t", object@crs, "\n")
            cat("data     \t tick \t count \t energy\tlenergy\ttime \n" )
            l.obj <- nrow(object)
            cat("   start:\t",  object@data$tick[1], "\t", object@data$count[1],
                "\t" ,object@data$energy[1], "\t" ,object@data$lenergy[1],
                "\t", as.character(object@simstart), "\n")
            cat("   mean:\t",  mean(object@data$tick), "\t", mean(object@data$count),
                "\t", mean(object@data$energy), "\t", mean(object@data$lenergy),
                "\t NA \n")
            if(!is.null(l.obj)) {
              cat("   end:\t",  object@data$tick[l.obj], "\t", object@data$count[l.obj],
                  "\t", object@data$energy[l.obj], "\t", object@data$lenergy[l.obj],
                  "\t NA")
            }
          }
)

#' @title Reading DEPONS simulation output
#' @description Function  for reading simulation output produced by DEPONS.
#'
# These
# describe movements of simulated animals within the simulation landscape, where
# the positions after each 30-min time step are provided using the coordinate
# reference system that were used for generating these landscapes.See
# van Beest et al. (2018) and Nabe-Nielsen et al. (2013) for details regarding
# how these files were generated as a balance between correlated random walk
# behaviour and spatial memory behaviour, which allows animals to return to
# previously visited food patches.
#'
#' @param fname Name of the file (character) that contains movement data
#' generated by DEPONS. The name includes the path to the directory if this is
#' not the current working directory.
#' @param title Optional character string giving name of simulation
#' @param landscape The landscape used in the simulation
#' @param simdate Optional POSIXlt object with date of simulation. If
#' not provided this is obtained from name of input file
#' @param crs Character, coordinate reference system (map projection)
#' @param simstart The start of the period that the  simulation represents, i.e.
#' the real-world equivalent of 'tick 1' (POSIXlt)
#' @return Returns an object with the elements \code{title}, \code{simdate},
#' \code{crs}, and ......   . The \code{date} is extracted from input data
#' if not provided explicitly and stored as a  \code{\link{POSIXlt}} object. The
#' element \code{tracks} is a list of objects of class
#' @export read.DeponsDyn
read.DeponsDyn <- function(fname, title="NA", landscape="NA", simdate="NA", crs=CRS(as.character(NA)),
                           simstart="NA") {
  raw.data <- utils::read.csv(fname, sep=";")
  # Get sim date and time from file name
  if (simdate=="NA")  simdate <- get.simdate(fname)
  all.data <- new("DeponsDyn")
  all.data@title <- title
  all.data@landscape <- landscape
  all.data@simdate <- simdate
  all.data@crs <- crs
  all.data@simstart <- simstart
  all.data$data <- utils::read.csv(fname, sep=";")
  return(all.data)
}


# all.data <- read.csv("Statistics.2020.Aug.27.10_55_36.csv", sep=";")
# fname <- "Statistics.2020.Aug.27.10_55_36.csv"
# uu <- read.DeponsDyn(fname)

